//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace Domain.Entities
{
    public partial class Category : StateObject
    {
        #region Primitive Properties
    
        public int CategoryID
        {
            get;
            set;
        }
    
        public string Name
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public FixupCollection<ContentContainer> ContentContainers
        {
            get
            {
                if (_contentContainers == null)
                {
                    var newCollection = new FixupCollection<ContentContainer>();
                    newCollection.CollectionChanged += FixupContentContainers;
                    _contentContainers = newCollection;
                }
                return _contentContainers;
            }
            set
            {
                if (!ReferenceEquals(_contentContainers, value))
                {
                    var previousValue = _contentContainers as FixupCollection<ContentContainer>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupContentContainers;
                    }
                    _contentContainers = value;
                    var newValue = value as FixupCollection<ContentContainer>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupContentContainers;
                    }
                }
            }
        }
        private FixupCollection<ContentContainer> _contentContainers;

        #endregion
        #region Association Fixup
    
        private void FixupContentContainers(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (ContentContainer item in e.NewItems)
                {
                    if (!item.Categories.Contains(this))
                    {
                        item.Categories.Add(this);
                    }
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (ContentContainer item in e.OldItems)
                {
                    if (item.Categories.Contains(this))
                    {
                        item.Categories.Remove(this);
                    }
                }
            }
        }

        #endregion
    }
}
