//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace Domain.Entities
{
    public partial class Comment : StateObject
    {
        #region Primitive Properties
    
        public int CommentID
        {
            get;
            set;
        }
    
        public string UserName
        {
            get;
            set;
        }
    
        public string CommentContent
        {
            get;
            set;
        }
    
        public string UserWebsite
        {
            get;
            set;
        }
    
        public Nullable<int> BlogPostID
        {
            get { return _blogPostID; }
            set
            {
                try
                {
                    _settingFK = true;
                    if (_blogPostID != value)
                    {
                        if (BlogPost != null && BlogPost.ContentID != value)
                        {
                            BlogPost = null;
                        }
                        _blogPostID = value;
                    }
                }
                finally
                {
                    _settingFK = false;
                }
            }
        }
        private Nullable<int> _blogPostID;
    
        public System.DateTime CommentDate
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public BlogPost BlogPost
        {
            get { return _blogPost; }
            set
            {
                if (!ReferenceEquals(_blogPost, value))
                {
                    var previousValue = _blogPost;
                    _blogPost = value;
                    FixupBlogPost(previousValue);
                }
            }
        }
        private BlogPost _blogPost;

        #endregion
        #region Association Fixup
    
        private bool _settingFK = false;
    
        private void FixupBlogPost(BlogPost previousValue)
        {
            if (previousValue != null && previousValue.Comments.Contains(this))
            {
                previousValue.Comments.Remove(this);
            }
    
            if (BlogPost != null)
            {
                if (!BlogPost.Comments.Contains(this))
                {
                    BlogPost.Comments.Add(this);
                }
                if (BlogPostID != BlogPost.ContentID)
                {
                    BlogPostID = BlogPost.ContentID;
                }
            }
            else if (!_settingFK)
            {
                BlogPostID = null;
            }
        }

        #endregion
    }
}
