//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace Domain.Entities
{
    public partial class MimeType : StateObject
    {
        #region Primitive Properties
    
        public int MimeID
        {
            get;
            set;
        }
    
        public string Name
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public FixupCollection<Media> Media
        {
            get
            {
                if (_media == null)
                {
                    var newCollection = new FixupCollection<Media>();
                    newCollection.CollectionChanged += FixupMedia;
                    _media = newCollection;
                }
                return _media;
            }
            set
            {
                if (!ReferenceEquals(_media, value))
                {
                    var previousValue = _media as FixupCollection<Media>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupMedia;
                    }
                    _media = value;
                    var newValue = value as FixupCollection<Media>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupMedia;
                    }
                }
            }
        }
        private FixupCollection<Media> _media;

        #endregion
        #region Association Fixup
    
        private void FixupMedia(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (Media item in e.NewItems)
                {
                    item.MimeType = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (Media item in e.OldItems)
                {
                    if (ReferenceEquals(item.MimeType, this))
                    {
                        item.MimeType = null;
                    }
                }
            }
        }

        #endregion
    }
}
