//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace Domain.Entities
{
    public partial class Page : ContentContainer
    {
        #region Primitive Properties
    
        public bool IsHomePage
        {
            get;
            set;
        }
    
        public bool IsNavigablePage
        {
            get;
            set;
        }

        #endregion
    }
}
