//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace Domain.Entities
{
    public partial class Position : StateObject
    {
        #region Primitive Properties
    
        public int PositionID
        {
            get;
            set;
        }
    
        public string Name
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public FixupCollection<GenericContentBlock> GenericContentBlocks
        {
            get
            {
                if (_genericContentBlocks == null)
                {
                    var newCollection = new FixupCollection<GenericContentBlock>();
                    newCollection.CollectionChanged += FixupGenericContentBlocks;
                    _genericContentBlocks = newCollection;
                }
                return _genericContentBlocks;
            }
            set
            {
                if (!ReferenceEquals(_genericContentBlocks, value))
                {
                    var previousValue = _genericContentBlocks as FixupCollection<GenericContentBlock>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupGenericContentBlocks;
                    }
                    _genericContentBlocks = value;
                    var newValue = value as FixupCollection<GenericContentBlock>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupGenericContentBlocks;
                    }
                }
            }
        }
        private FixupCollection<GenericContentBlock> _genericContentBlocks;

        #endregion
        #region Association Fixup
    
        private void FixupGenericContentBlocks(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (GenericContentBlock item in e.NewItems)
                {
                    item.Position = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (GenericContentBlock item in e.OldItems)
                {
                    if (ReferenceEquals(item.Position, this))
                    {
                        item.Position = null;
                    }
                }
            }
        }

        #endregion
    }
}
